### PR TITLE
Added button to change period of live data

### PR DESCRIPTION
**Pull request by CBarrett2**
There seems to be a bug where sometimes while loading 12 hour data no data is returned between ~3 and 15th august. I am sure the right request is being made though! 

Also wondering if now is a good time to split the data stuff out into a separate class, which contains ohlcWebsocketConverter and historicFeed, and deals with invalidating callbacks/changing both periods at once/ setting date start/ends automatically

### CODE REVIEW

**Comment by CBarrett2** [comment]
The aforementioned bug seems to be something which only occurs between those dates, at whatever period, but only intermittently - sometimes the exact same steps will end in that data being loaded, and other times not.

**Comment by CBarrett2** [comment]
Resolves #179

**Comment by jleft** [comment]
Could any of this be pulled out of main, into a new components? Especially the interaction logic.

**Comment by CBarrett2** [comment]
Created  #206, where I tried to pull this out of main, not sure if that's what you had in mind?

**Pull request closed without merging**
