### PR TITLE
Refactor models and add UID component to generate IDs for keys

### PR DESCRIPTION
**Pull request by jleft**
Still a WIP, but thought I'd put this up for some feedback. #410 

Some areas to consider:
- Should we be consistent with how we pass configuration values to the models? If so, which approach should we use? Currently, it's either several params (e.g. `sc.model.menu.option`) or a single config object (e.g. `sc.model.data.product`).
- I think adding an `id` property to the renders, so we can key on the `id` is good (or at least better than `isLine`) and should make future work (e.g. additive indicators) easier. Not so keen on the implementation - there is repetition. Perhaps we should make own series/indicator components which wrap the d3fc components and add the `id` to them?
- Should models have default values?
- Should we instantiate series/indicator components outside of `sc.model.whatever`? We could do this in a similar way to period and products, which are instantiated in app.js.

### CODE REVIEW

**Comment by jdhodges431** [comment]
We could use config objects if the number of parameters becomes unreasonably long. This doesn't seem to be the case at the moment - could this be an issue in the future?

**Comment by tlsim** [comment]
I'm happy to see this merged now and we can decide on the points raised later.

**Comment by djmiley** [comment]
I agree with @tlsim

**Comment by jleft** [comment]
> We could use config objects if the number of parameters becomes unreasonably long. This doesn't seem to be the case at the moment - could this be an issue in the future?

Yeah, definitely a good idea - a long list of unnamed params is not nice! Agreed, something to bear in mind for the future.

**Pull request merged**
