### PR TITLE
Displays moving average line in bollinger bands indicator.

### LINKED ISSUE #500: Bollinger bands should include the central moving average line
This was probably removed for cosmetic reasons, however it is an important component of the indicator.

### PR DESCRIPTION
**Pull request by jdhodges431**
Fixes #500.

### CODE REVIEW

**Comment by djmiley** [comment]
Is there UX thoughts on the color of this? i'm guessing it's going to default to d3fc.css styling. 
LGTM other than that.

**Comment by jdhodges431** [comment]
It's definitely worth considering. There isn't anything specific in the UX spec, but some of the images show the colour as being the same as the moving average indicator. Don't think it would make sense for them to be exactly the same colour though.

**Comment by jleft** [comment]
I think it'll default to `@secondary-orange`?

As orange is used for the primary series, I think it could be pretty confusing, especially if the line series is selected. If this is the case, then I'd consider changing its colour to a tertiary (maybe purple or pink) colour.

Using a tertiary colour would fit with the designs too:

> The Tertiary colours are generally used for the indicators.

**Comment by jleft** [comment]
Another option could be to use a dashed line.

**Comment by jleft** [comment]
:+1:

**Pull request merged**
