### PR TITLE
Reset button changes view domain to the last 50 datums (or fewer if there are fewer than 50 data points)

### PR DESCRIPTION
**Pull request by CBarrett2**

### CODE REVIEW

**Comment by djmiley** [comment]
I'm happy to let the golden ratio go, for reasons of consistency.

**Comment by CBarrett2** [comment]
The end of an era :(

**Comment by djmiley** [comment]
It's worth thinking whether a number of data points related to period is a better measure to show?

So is a 1/4 or 50 data points better for now?

**Comment by djmiley** [comment]
But `navAspect` is beginning to look more and more like an ugly variable.

**Comment by CBarrett2** [comment]
Yes, number of data points would be better actually

**Comment by djmiley** [comment]
I agree. :)

**Comment by CBarrett2** [comment]
Resolves #136

**Comment by djmiley** [comment]
Looks good.

**Pull request merged**
